apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::440093363600:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M1LGG7M9ZC31
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::440093363600:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-07T02:15:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1537"
  uid: 6d03be99-c6cd-424e-b4dc-c2c58c98e761
